CREATE TABLE IF NOT EXISTS  t_fill_performance (
	id BIGINT(20) NOT NULL,
	a VARCHAR(30) NULL DEFAULT NULL ,
	b VARCHAR(30) NULL DEFAULT NULL ,
	c VARCHAR(30) NULL DEFAULT NULL ,
	d VARCHAR(30) NULL DEFAULT NULL ,
	e VARCHAR(30) NULL DEFAULT NULL ,
	f VARCHAR(30) NULL DEFAULT NULL ,
	g VARCHAR(30) NULL DEFAULT NULL ,
	h VARCHAR(30) NULL DEFAULT NULL ,
	i VARCHAR(30) NULL DEFAULT NULL ,
	j VARCHAR(30) NULL DEFAULT NULL ,
	k VARCHAR(30) NULL DEFAULT NULL ,
	l VARCHAR(30) NULL DEFAULT NULL ,
	m VARCHAR(30) NULL DEFAULT NULL ,
	n VARCHAR(30) NULL DEFAULT NULL ,
	PRIMARY KEY (id)
);
