CREATE TABLE IF NOT EXISTS  h2person (
	testId BIGINT(20) NOT NULL AUTO_INCREMENT,
	name VARCHAR(30) NULL DEFAULT NULL ,
	age INT(11) NULL DEFAULT NULL ,
	testType INT(11) NULL ,
	testDate DATETIME NULL DEFAULT NULL,
	price DECIMAL(10,2) NULL DEFAULT NULL,
	desc VARCHAR(30) NULL DEFAULT NULL ,
	version INT(5) NULL DEFAULT NULL,
	lastUpdatedDt TIMESTAMP NULL,
	PRIMARY KEY (testId)
)

