CREATE TABLE IF NOT EXISTS  h2user (
	test_id BIGINT(20) NOT NULL AUTO_INCREMENT,
	name VARCHAR(30) NULL DEFAULT NULL ,
	age INT(11) NULL DEFAULT NULL ,
	test_type INT(11) NULL ,
	test_date DATETIME NULL DEFAULT NULL,
	price DECIMAL(10,2) NULL DEFAULT NULL,
	desc VARCHAR(30) NULL DEFAULT NULL ,
	version INT(5) NULL DEFAULT NULL,
	last_updated_dt TIMESTAMP NULL,
	deleted INT(1) NULL DEFAULT 0 ,
	PRIMARY KEY (test_id)
);
COMMENT ON COLUMN h2user.test_id IS 'PK';
COMMENT ON COLUMN h2user.name IS 'USERNAME';


