CREATE TABLE IF NOT EXISTS  key_generator_model (
	id BIGINT(20) NOT NULL AUTO_INCREMENT,
	name VARCHAR(30) NULL DEFAULT NULL ,
	grade INT(3) NULL,
	gender VARCHAR(10) NULL,
	age INT(11) NULL DEFAULT NULL ,
	PRIMARY KEY (id)
);

CREATE SEQUENCE key_generator_model_seq START WITH 1 INCREMENT BY 10;

