CREATE TABLE IF NOT EXISTS  t_i171cq_long (
	id BIGINT(20) NOT NULL,
	name VARCHAR(30) NULL DEFAULT NULL ,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS  t_i171cq_string (
	id varchar NOT NULL,
	name VARCHAR(30) NULL DEFAULT NULL ,
	PRIMARY KEY (id)
);

